[project]
name = "robotvision"
version = "0.1.0"
description = "Robot Vision ML@P 25-26"
authors = [{name = "Manav Gagvani", email = "mgagvani@purdue.edu"}]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipython>=8.23.0",
    "waymo-open-dataset-tf-2-12-0==1.6.7",
]
